### PR TITLE
Update to Weatherman v76

### PR DESCRIPTION
**Pull request by Sineos**
- Update to v76 field names
- Add new v76 fields
- Harmonize some value descriptions
- Delete "Bodenfeuchte"
- Add some min and max values

### CODE REVIEW

**Comment by t4qjXH8N** [comment]
Hey thank you very much for your contribution! I haven't checked the code yet, but does that mean that after merging Weathermans with firmwares lower than v76 would not work anymore? 

I was thinking of adding a version tag into wiffi_config.json, such that the adapter has the possibility to select the right set of values. This would have the adavantage that further changes in the datagram in the future could easily be added while preserving backward compatibity. What do you think?

I could implement the version feature during the weak and then accept your pull request (and add a version tag for v76).

**Comment by Sineos** [comment]
Yes, the changes in v76 are breaking backwards compatibility. I just updated to v76 and noticed it stopped working, so this PR is sort of my quick fix.
Possibly the easiest solution would be to a definition set `Weatherman <v76` and `Weatherman v76+`

**Comment by t4qjXH8N** [comment]
Thanks for your thoughts, I thought about future wiffi updates too. Simply taking the datanames from the datagram would have also some additional drawback. Besides name, unit and description we also have to set the role correctly, especially in the case of the Weatherman. There are so many disitinct roles assoicated with the datapoints that one would have to setup a large switch-clause or, maybe better, a external json file that maps some known datapoints to the correct roles. And then we end up at the same problem that we already have now: We have to maintain a config for mapping the roles. 

In my opinion the easiest way is to maintain the config file and introduce the version attribute, at the moment.

**Comment by Sineos** [comment]
Agreed. 
One further comment: When updating the definition file `wiffi_config.json`, I had to remove my Weatherman entry and readd it, otherwise the adapter would not pickup the changed names.

I guess this needs to be highlighted somewhere, e.g. readme, changelog etc.

**Comment by t4qjXH8N** [comment]
Thank you very much for the new datapoints. The current version 2.0.0 dynamically creates or removes datapoints according to the datagram send by the Wiffi. Special roles or other state attributes as unit can be added with the state_extensions.json file.

**Pull request closed without merging**
